---
- name: Use FIPS compliant algorithms for encryption, hashing, and signing
  win_regedit:
    path: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\FIPSAlgorithmPolicy\
    name: "Enabled"
    data: "1"
    type: dword